[providers]
providers = ['php']

[variables]
NIXPACKS_PHP_VERSION = '8.2'
NIXPACKS_PHP_EXTENSIONS = 'pdo, pdo_pgsql, pgsql, redis, bcmath, mbstring, xml, zip, gd, curl, intl'

[phases.setup]
nixPkgs = ['...', 'roadrunner']

[phases.build]
cmds = [
    'composer install --no-dev --optimize-autoloader',
    'php artisan config:cache',
    'php artisan route:cache',
    'php artisan view:cache'
]
