[providers]
providers = ['php']

[variables]
NIXPACKS_PHP_VERSION = '8.4'
NIXPACKS_PHP_EXTENSIONS = 'pdo, pdo_pgsql, pgsql, redis, bcmath, mbstring, xml, zip, gd, curl, intl, sockets, opcache'

[phases.build]
cmds = [
    'composer install --no-dev --optimize-autoloader --ignore-platform-reqs',
    'php artisan config:clear',
    'php artisan route:clear',
    'php artisan view:clear'
]

[phases.setup]
nixPkgs = ["...", "postgresql_15"]
